FROM tomcat:7-jre7
#RUN rm  -rf /usr/local/tomcat/conf/server.xml
RUN rm  -rf /usr/local/tomcat/bin/catalina.sh
RUN echo "Asia/Shanghai" > /etc/timezone
ADD tomcatfile-to-containerfile/catalina.sh /usr/local/tomcat/bin/catalina.sh
